#!/bin/python3

from scapy.all import srp, ARP, Ether

target_ip = 

arp = ARP(pdst=target_ip)

ether = Ether(dst="ff:ff:ff:ff:ff:ff")

packet = ether/arp

result = srp(packet, timeout=3, verbose=0)[0]

clients = []

for sent, received in result:

    clients.append({'ip': received.psrc, 'mac': received.hwsrc})

print('Devices on network: ')
print("IP" + " "*18+"MAC")
for client in clients:
    print("{:16}    {}".format(client['ip'], client['mac']))
